name: Deploy React App COMP2156 DevOps Project CI
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€

on:
  pull_request:
    branches: ["main"] # Adjust this to your main branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x" # Use the appropriate Node.js version for your project

      # Cache Node.js modules
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules # Take any latest cache if failed to find it for current package-lock.json  
          
      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build React app
      - name: Build the app
        run: npm run build

      # Run tests
      - name: Run test
        run: npm run test

      # Upload build artifacts for deployment
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./build # Upload the build directory as an artifact for deployment

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"